name: full_workout
description: A new Flutter application.

version: 1.7.1+13

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  sqflite: ^2.0.0+3
  font_awesome_flutter: ^9.2.0
  eva_icons_flutter: ^3.0.0
  toggle_switch: ^1.2.0
  day_night_time_picker: ^1.0.5
  connectivity_plus: ^2.2.0
  flutter_local_notifications: ^9.2.0
  flutter_bloc: ^8.0.1
  share_plus: ^3.0.4
  shared_preferences: ^2.0.6
  flutter_tts: ^3.1.0
  flutter_phoenix: ^1.0.0
  audiofileplayer: ^2.0.1
  youtube_player_flutter: ^8.0.0
  flutter_svg: ^1.0.3
  confetti: ^0.6.0
  screenshot: ^1.2.3
  timelines: ^0.1.0
  percent_indicator: ^4.0.0
  flutter_rating_bar: ^4.0.0
  url_launcher: ^6.0.6
  wakelock: ^0.6.1+1
  intl: ^0.17.0
  animated_text_kit: ^4.2.1
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.0
  month_picker_dialog: ^0.4.0
  fluttertoast: ^8.0.6
  fl_chart: ^0.41.0
  animated_background: ^2.0.0
  flutter_slidable: ^1.2.0
  rxdart: ^0.26.0
  flutter_native_timezone: ^2.0.0
  dashed_circle: ^0.0.2
  flutter_rounded_date_picker: ^2.0.2
  sliding_sheet: ^0.5.0
  numberpicker: ^2.1.1
  flutter_material_pickers: ^3.1.0
  flutter_email_sender: ^5.0.2
  text_to_speech: ^0.2.3
  rate_my_app: ^1.1.1
  android_intent_plus: ^3.1.0
  device_info_plus: ^3.2.1
  in_app_purchase: ^2.0.1
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_countdown_timer: ^4.1.0
  flutter_custom_clippers: ^2.0.0
  dotted_border: ^2.0.0+2
  provider: ^6.0.2
  adaptive_theme: ^2.3.0
  flutter_signin_button: ^2.0.0
  google_mobile_ads: ^1.1.0
  flutter_markdown: ^0.6.9
  flutter_sticky_header: ^0.6.1
  google_sign_in: ^5.3.0
  firebase_auth: ^3.3.14
  cloud_firestore: ^3.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.3.2
  flutter_lints: ^1.0.0

#flutter_native_splash:
#  color: "#0362fc"
#  image: "assets/splash.png"
#  android: true
#  ios: true
#  android_gravity: fill


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/explore_image/
    - assets/all-workouts/
    - assets/other/
    - assets/sound/
    - assets/home_cover/
    - assets/workout_list_cover/
    - assets/icons/