name: full_workout
description: A new Flutter application.

version: 1.9.2+24

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  sqflite: ^2.0.0+3
  font_awesome_flutter: ^9.2.0
  eva_icons_flutter: ^3.0.0
  toggle_switch: ^2.0.1
  day_night_time_picker: ^1.1.2
  connectivity_plus: ^2.2.0
  flutter_local_notifications: ^9.2.0
  flutter_bloc: ^8.0.1
  share_plus: ^4.0.4
  shared_preferences: ^2.0.6
  flutter_tts: ^3.5.1
  flutter_phoenix: ^1.0.0
  audiofileplayer: ^2.1.0
  youtube_player_flutter: ^8.1.0
  flutter_svg: ^1.0.3
  confetti: ^0.7.0
  screenshot: ^1.2.3
  timelines: ^0.1.0
  percent_indicator: ^4.0.0
  flutter_rating_bar: ^4.0.0
  url_launcher: ^6.0.6
  wakelock: ^0.6.1+1
  intl: ^0.17.0
  animated_text_kit: ^4.2.1
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.0
  month_year_picker: ^0.2.0+2
  fluttertoast: ^8.0.6
  fl_chart: ^0.55.0
  animated_background: ^2.0.0
  flutter_slidable: ^1.2.0
  rxdart: ^0.26.0
  flutter_native_timezone: ^2.0.0
  dashed_circle: ^0.0.2
  flutter_rounded_date_picker: ^3.0.1
  sliding_sheet: ^0.5.2
  numberpicker: ^2.1.1
  flutter_email_sender: ^5.0.2
  text_to_speech: ^0.2.3
  rate_my_app: ^1.1.3
  android_intent_plus: ^3.1.0
  device_info_plus: ^4.0.0
  in_app_purchase: ^3.0.4
  carousel_slider: ^4.0.0
  loading_indicator: ^3.1.0
  smooth_page_indicator: ^1.0.0+2
  flutter_countdown_timer: ^4.1.0
  flutter_custom_clippers: ^2.0.0
  dotted_border: ^2.0.0+2
  provider: ^6.0.2
  adaptive_theme: ^3.0.0
  flutter_signin_button: ^2.0.0
  google_mobile_ads: ^1.1.0
  flutter_markdown: ^0.6.9
  nepali_date_picker: ^5.3.0
  modal_bottom_sheet: ^2.0.1
  flutter_sticky_header: ^0.6.1
  google_sign_in: ^5.3.0
  loading_animation_widget: ^1.2.0+1
  flutter_facebook_auth: ^4.3.4
  firebase_auth: ^3.3.14
  cloud_firestore: ^3.1.12
  animated_splash_screen: ^1.2.0
  bubble_bottom_bar: ^2.0.0
  purchases_flutter: ^3.10.0
  animations: ^2.0.2
  awesome_dialog: ^2.2.1
  flutter_material_pickers: ^3.1.4+1
  shimmer: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  just_audio: ^0.9.28
  convex_bottom_bar: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.1.6
  flutter_lints: ^2.0.1

#flutter_native_splash:
#  color: "#0362fc"
#  image: "assets/splash.png"
#  android: true
#  ios: true
#  android_gravity: fill


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/explore_image/
    - assets/all-workouts/
    - assets/other/
    - assets/sound/
    - assets/home_cover/
    - assets/workout_list_cover/
    - assets/icons/
