name: full_workout
description: A new Flutter application.

version: 2.1.6+38

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1
  provider: ^6.0.5
  intl: ^0.18.1
  fluttertoast: ^8.2.2
  google_fonts: ^6.1.0
  flutter_email_sender: ^6.0.2
  font_awesome_flutter: ^10.6.0
  android_intent_plus: ^4.0.3
  numberpicker: ^2.1.2
  shared_preferences: ^2.2.2
  flutter_tts: ^3.8.3
  flutter_countdown_timer: ^4.1.0
  adaptive_theme: ^3.4.1
#  flutter_native_timezone: ^2.0.0
  audiofileplayer: ^2.1.1
  loading_indicator: ^3.1.1
  flutter_markdown: ^0.6.18+2
  day_night_time_picker: ^1.3.0+1
#  modal_bottom_sheet: any
  rate_my_app: ^2.0.0
  rxdart: ^0.27.7
  firebase_core: ^2.21.0
  flutter_phoenix: ^1.0.0
  sqflite: ^2.3.0
  carousel_slider: ^4.2.1
  percent_indicator: ^4.2.3
  rename: ^3.0.1
  cupertino_icons: ^1.0.6
  google_mobile_ads: ^3.1.0
  awesome_dialog: ^3.1.0
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.12.2
  month_year_picker: ^0.3.0+1
  flutter_staggered_animations: ^1.1.1
  table_calendar: ^3.0.9
  fl_chart: ^0.64.0
  toggle_switch: ^2.1.0
  youtube_player_flutter: ^8.1.2
  flutter_bloc: ^8.1.3
  wakelock_plus: ^1.1.3
  flutter_svg: ^2.0.9
  confetti: ^0.7.0
  dots_indicator: ^3.0.0
  screenshot: ^2.1.0
  animator: ^3.3.0
  eva_icons_flutter: ^3.1.0
  dotted_border: ^2.1.0
  path_provider: ^2.1.1
  month_picker_dialog: ^2.2.1
  path: ^1.8.3
  device_info_plus: ^9.1.0
  share_plus: ^7.2.1
  connectivity_plus: ^5.0.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  flutter_local_notifications: ^16.2.0
  purchases_flutter: ^6.2.0
  dashed_circle: ^0.0.2
  timelines: ^0.1.0
  firebase_auth: ^4.12.1
  slide_countdown: ^1.3.2
  firebase_crashlytics: ^3.4.8
  firebase_messaging: ^14.7.8
 



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.1.6
  flutter_lints: ^2.0.1




flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/explore_image/
    - assets/all-workouts/
    - assets/other/
    - assets/sound/
    - assets/home_cover/
    - assets/workout_list_cover/
    - assets/icons/
