name: full_workout
description: A new Flutter application.

version: 1.9.3+25

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.5
  provider: ^6.0.3
  intl: ^0.17.0
  fluttertoast: ^8.0.9
  google_fonts: ^3.0.1
  flutter_email_sender: ^5.1.0
  font_awesome_flutter: ^10.1.0
  android_intent_plus: ^3.1.5
  numberpicker: ^2.1.1
  shared_preferences: ^2.0.15
  text_to_speech: ^0.2.3
  flutter_tts: ^3.6.1
  date_time_picker: ^2.1.0
  flutter_countdown_timer: ^4.1.0
  adaptive_theme: ^3.1.1
  flutter_native_timezone: ^2.0.0
  audiofileplayer: ^2.1.0
  loading_indicator: ^3.1.0
  flutter_markdown: ^0.6.10+3
  day_night_time_picker: ^1.1.2
  modal_bottom_sheet: ^2.1.0
  rxdart: ^0.27.5
  rate_my_app: ^1.1.3
  firebase_core: ^2.1.1
  flutter_phoenix: ^1.0.0
  convex_bottom_bar: ^3.0.0
  sqflite: ^2.0.3+1
  carousel_slider: ^4.1.1
  percent_indicator: ^4.2.2
  rename: ^2.0.1
  cupertino_icons: ^1.0.2
  google_mobile_ads: ^2.0.1
  awesome_dialog: ^3.0.1
  google_sign_in: ^5.4.1
  firebase_auth: ^4.1.1
  cloud_firestore: ^4.0.4
  month_year_picker: ^0.2.0+2
  flutter_staggered_animations: ^1.1.1
  table_calendar: ^3.0.7
  sliding_sheet: ^0.5.2
  fl_chart: ^0.55.1
  toggle_switch: ^2.0.1
  youtube_player_flutter: ^8.1.0
  flutter_bloc: ^8.0.1
  wakelock: ^0.6.2
  flutter_svg: ^1.1.5
  confetti: ^0.7.0
  dots_indicator: ^2.1.0
  screenshot: ^1.2.3
  animator: ^3.2.0
  eva_icons_flutter: ^3.1.0
  draggable_home: ^1.0.4
  dotted_border: ^2.0.0+3
  flutter_datetime_picker: ^1.5.1
  path_provider: ^2.0.11
  path: ^1.8.2
  device_info_plus: ^4.1.0
  share_plus: ^4.0.10+1
  flutter_local_notifications: ^9.7.0
  connectivity_plus: ^2.3.6+1
  smooth_page_indicator: ^1.0.0+2
  shimmer: ^2.0.0
  cached_network_image: ^3.2.2
  purchases_flutter: ^3.10.0
  dashed_circle: ^0.0.2
  timelines: ^0.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.1.6
  flutter_lints: ^2.0.1

#flutter_native_splash:
#  color: "#0362fc"
#  image: "assets/splash.png"
#  android: true
#  ios: true
#  android_gravity: fill


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/explore_image/
    - assets/all-workouts/
    - assets/other/
    - assets/sound/
    - assets/home_cover/
    - assets/workout_list_cover/
    - assets/icons/
