name: full_workout
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  sqflite: ^2.0.0+3
  flutter_icons: ^1.1.0
  eva_icons_flutter: ^3.0.0
  cached_network_image: ^3.0.0
  get_it: ^7.1.3
  toggle_switch: ^1.2.0
  share: ^2.0.1
  flutter_easyloading: ^3.0.0
  shared_preferences: ^2.0.6
  flutter_tts: ^3.1.0
  # audioplayers: ^0.19.0
  youtube_player_flutter: ^8.0.0
  flutter_svg: ^0.22.0
  confetti: ^0.5.5
  screenshot: ^0.3.0
  timelines: ^0.1.0
  percent_indicator: ^3.0.1
  flutter_rating_bar: ^4.0.0
  url_launcher: ^6.0.6
  wakelock: ^0.5.2
  device_info: ^2.0.2
  intl: ^0.17.0
  flutter_local_notifications: ^6.0.0
  table_calendar: ^3.0.0
  charts_flutter: ^0.10.0
  charts_painter: ^1.1.0
  chart_sparkline: ^1.0.5
  flutter_echarts: ^2.1.0
  k_chart: ^0.3.1
  line_chart: ^1.1.11
  smoothie: ^0.3.0+1
  animated_text_kit: ^4.2.1
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.7
  infinite_listview: ^1.1.0
  month_picker_dialog: ^0.4.0
  fl_chart: ^0.36.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.2.0

flutter_native_splash:
  color: "#0362fc"
  image: "assets/splash_full.png"
  android: true
  ios: true
  android_gravity: fill


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/cover/
    - assets/bg_cover/
    - assets/splash/
    - assets/all-workouts/
    - assets/other/
    - assets/animated-cover/

